### ISSUE TITLE
[Bug] When pressing the Control key (Windows), the collections containing an item do not highlight.

### ISSUE THREAD

**Issue by WMAM** [tefkah/zotero-night#34]
In the main Zotero Tab (library), in night view, when pressing the Control key (Windows), the collections containing an item do not highlight.
Zotero: 6.0.7
Zotero-night plugin: 0.4.8

**Comment by lukelbd** [comment]
I have the same issue pressing the alt key on mac. Without the plugin, pressing alt highlights the subsellection(s) containing the item.

**Comment by lukelbd** [comment]
This feature is documented on the zotero website [here](https://www.zotero.org/support/kb/collections_containing_an_item).

**Comment by daeh** [comment]
Echoing this. Absolutely love the plugin, but I make heavy use of the Option-key highlighting of containing collections. This is the only essential feature that I'm missing in dark mode. Thanks for the fantastic work! (duplicate issue posted in #43)

**Comment by fiftyfathoms** [comment]
Although your amazing add-on makes it possible to quickly switch to the light theme temporarily to be able to use this feature of Zotero, it would give poor eyes a shock and therefore it is not an ideal workaround. I would like to ask for a fix for this bug as well.

**Comment by dstillman** [comment]
@tefkah: Could you please fix this? We can't allow a plugin to break basic Zotero functionality — it confuses users and creates a [support burden](https://forums.zotero.org/discussion/97562/pressing-ctrl-key-doesnt-show-collections) in the forums.

**Comment by tefkah** [comment]
Expect a fix soon!

**Comment by tefkah** [comment]
This should be fixed in https://github.com/tefkah/zotero-night/releases/tag/v0.4.10 !

**Comment by daeh** [comment]
It doesn't seem to work for me (Mac)
Zotero  6.0.10
Zotero-night 0.4.10
MacOS 12.4

With the plugin install, in day mode, option key highlights containing collections, in night mode, option key does not highlight containing collections (the collection browser will still jump, but there's no visual highlight)

**Comment by pascaloettli** [comment]
> This should be fixed in https://github.com/tefkah/zotero-night/releases/tag/v0.4.10 !

It is not fixed
Zotero 6.0.10
Night for Zotero 0.4.13
MacOS 12.4

**Comment by tefkah** [comment]
Hmmm, strange, it does seem to work for me, it also updated correctly for me.

MacOS Zotero 6.0.12-beta.2+fc0f6157d

https://user-images.githubusercontent.com/21983833/181494733-2d76ffcc-e38f-43c0-a414-f63fbb76919e.mov

**Comment by tefkah** [comment]
Or is this some other functionality than I'm thinking about

**Comment by tefkah** [comment]
Ahhh okay, give me a second

**Comment by tefkah** [comment]
This should now _actually_ work!

**Comment by lukelbd** [comment]
Works perfectly now! And the highlighting is even more obvious + useful than when using the light theme 😀. Thanks so much!

**Comment by pascaloettli** [comment]
> This should now _actually_ work!

I confirm it now works. Thank you
