### ISSUE TITLE
Highlighting collections containing an item feature broken

### ISSUE THREAD

**Issue by assombrance** [tefkah/zotero-night#43]
As mentioned in this post:
https://www.zotero.org/support/kb/collections_containing_an_item
Zotero allows you to highlight the collections containing an item by holding down the `OPT` key (macOS), `CTRL` key (Windows), or `ALT` key (Linux).

Unfortunately, it seems that the extension as is overnights the background color of the highlighted elements.

The dark mode toggle button fortunately allows the simple workaround of disabling the dark mode to find the element, but the experience could be even better!

Thank you for the great work anyway :D

**Comment by daeh** [comment]
Echoing this. Absolutely love the plugin, but I make heavy use of the Option-key highlighting of containing collections. This is the only essential feature that I'm missing in dark mode. Thanks for the fantastic work!

**Comment by tefkah** [comment]
Should be fixed!

**Comment by v-marinkov** [comment]
> Should be fixed!

I just tried it on 0.4.13 on Windows and it still isn't working in dark mode

**Comment by v-marinkov** [comment]
@tefkah I confirm it's fixed in 0.4.14 :) Many thanks!

**Comment by fiftyfathoms** [comment]
@tefkah Confirm it's fixed and working properly on Windows with version 0.4.15. Many many thanks.
